### ISSUE TITLE
Limits in the pinocchio model of the robot wrapper are now numpy array in python

### ISSUE THREAD

**Issue by NoelieRamuzat** [stack-of-tasks/sot-talos#14]
In the talos.py python script the bounds of the robot are defined using the limits of the robot model in pinocchio:
 https://github.com/stack-of-tasks/sot-talos/blob/bc826e5093d8c240ea584ceffbffd210933df73e/src/dynamic_graph/sot/talos/talos.py#L93-L98 

However these limits are accessed as if they were numpy matrix. Following the new upgrade of pinocchio they are now numpy arrays.

Launching a simulation with talos is thus crashing.
The following update fix the problem:

```
self.device.setPositionBounds(self.pinocchioModel.lowerPositionLimit[1:],
                              self.pinocchioModel.upperPositionLimit[1:])
self.device.setVelocityBounds((-self.pinocchioModel.velocityLimit),
                               self.pinocchioModel.velocityLimit)
self.device.setTorqueBounds((-self.pinocchioModel.effortLimit),
                             self.pinocchioModel.effortLimit)
```

**Comment by nim65s** [comment]
Sorry for this, I already fixed that yesterday here: 
https://github.com/Gepetto/robotpkg-wip/blob/master/py-sot-talos/patches/patch-aa

And I did not yet open the PR :/

**Comment by jmirabel** [comment]
EigenPy defaults has changed from numpy.matrix to numpy.array. There are plenty of places in SoT where the code should be updated in order to be compatible with numpy array. Your patch in only one of them.

If you do not want to update all the Python code of SoT, you can add the following lines to the prologue (as early as possible :) )
```python
import eigenpy
eigenpy.switchToNumpyMatrix()
```

**Comment by jmirabel** [comment]
> Sorry for this, I already fixed that yesterday here:
https://github.com/Gepetto/robotpkg-wip/blob/master/py-sot-talos/patches/patch-aa
> 
> And I did not yet open the PR :/

@nim65s Please, do not do that. sot-core and sot-tools, at least, should be updated first.

**Comment by nim65s** [comment]
sot-core & sot-tools unit tests are passing with eigenpy v2 and np.array by default. If there are other things to change, we have to open issues for that.

Do you want me to remove this patch for the binary package, and switch back to np.matrix ?

**Comment by jmirabel** [comment]
Did you run @olivier-stasse 's integration tests ?

**Comment by jmirabel** [comment]
https://github.com/stack-of-tasks/sot-core/issues/127

**Comment by nim65s** [comment]
I did.

**Comment by jmirabel** [comment]
@nim65s is this solved now ?
