### ISSUE TITLE
instanciation of abstract class

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/sot-talos#19]
Hi,

https://github.com/stack-of-tasks/sot-talos/blob/64bec0f0b9f570da8a421bfd2439189e2cbfb80a/src/dynamic_graph/sot/pyrene/prologue.py#L31

Running talos integration tests raised the following issue:
```python
  File "/opt/openrobots/lib/python2.7/site-packages/dynamic_graph/sot/pyrene/prologue.py", line 31, in makeRobot
    robot = Robot(name='robot', device=DeviceTalos('PYRENE'), fromRosParam=True)
TypeError: Can't instantiate abstract class Robot with abstract methods defineHalfSitting
```

https://github.com/stack-of-tasks/sot-dynamic-pinocchio/blob/f3e0e8a98a6864259c3985c167e42082cd6a5d28/src/dynamic_graph/sot/dynamic_pinocchio/humanoid_robot.py#L236

So I think I just need to make a release.

**Comment by jmirabel** [comment]
Is sot-dynamic-pinocchio up to date too ?

**Comment by nim65s** [comment]
Fixed with the release :)
