### ISSUE TITLE
Dependency to pyrene-motions has become required

### ISSUE THREAD

**Issue by florent-lamiraux** [stack-of-tasks/sot-talos#27]
in commit a866113a8ed85aca3147a044af8f93212f653ddb. Is there a good reason for that ?
This package is not accessible on github.

https://github.com/stack-of-tasks/sot-talos/blob/bf5e7afc78e8c64f0aebae5ea4f37ae7af45c789/CMakeLists.txt#L41

**Comment by olivier-stasse** [comment]
@florent-lamiraux 
Sorry for that, the package is now available.
Thanks a lot for raising the issue.
